export default [
    "Don't ping me again, __***bitch***__.",
    "Stop pinging me.",
    "Bruh what the fuck *why*?",
    "I __swear__ I will turn off notifications.",
    "Please stop pinging me or else **I will delete all your hard work and make you start over**.",
    "You suck.",
    "I just unsubscribed from your YouTube channel.",
    "**no u**",
    "FUCK YOU",
    "DONT FUCKING PING ME",
    "why u do dis",
    "no pls",
    "I was watching __anime__ bruh.",
    "Can you like, *not* ping me?",
    "im blocking ur ass",
];
